version: '1.0'
stages:
  - test
  - build
steps:
  MyUnitTests:
    title: Unit test
    stage: test
    image: 'golang:1.12'
    commands:
      - go test -v
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: demo 
    working_directory: ./
    tag: modules
    dockerfile: Dockerfile.mod
